// Auto-generated by ffigen from native/icon_shim.h. Do not edit.
//
// Regenerate:
//   dart run ffigen --config native/ffigen_icon.yaml

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Dart FFI bindings for bardash icon_shim (GTK + librsvg)
class IconShimBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  IconShimBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  IconShimBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void icon_shim_free_string(ffi.Pointer<ffi.Char> str) {
    return _icon_shim_free_string(str);
  }

  late final _icon_shim_free_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'icon_shim_free_string',
      );
  late final _icon_shim_free_string = _icon_shim_free_stringPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> icon_shim_lookup(
    ffi.Pointer<ffi.Char> icon_name,
    int size,
    ffi.Pointer<ffi.Char> theme_name,
  ) {
    return _icon_shim_lookup(icon_name, size, theme_name);
  }

  late final _icon_shim_lookupPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('icon_shim_lookup');
  late final _icon_shim_lookup = _icon_shim_lookupPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
        )
      >();

  int icon_shim_raster_svg(
    ffi.Pointer<ffi.Char> svg_path,
    ffi.Pointer<ffi.Char> png_path,
    int w,
    int h,
  ) {
    return _icon_shim_raster_svg(svg_path, png_path, w, h);
  }

  late final _icon_shim_raster_svgPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Int,
          )
        >
      >('icon_shim_raster_svg');
  late final _icon_shim_raster_svg = _icon_shim_raster_svgPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int, int)
      >();

  ffi.Pointer<ffi.Char> icon_shim_version() {
    return _icon_shim_version();
  }

  late final _icon_shim_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'icon_shim_version',
      );
  late final _icon_shim_version = _icon_shim_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();
}
