// Generated by dart-wayland-scanner
// https://github.com/your-repo/dart-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/main/staging/xdg-session-management/xdg-session-management-v1.xml
//
// xdg_session_management_v1 Protocol Copyright: 
/// 
/// Copyright 2018 Mike Blumenkrantz
/// Copyright 2018 Samsung Electronics Co., Ltd
/// Copyright 2018 Red Hat Inc.
/// 
/// Permission is hereby granted, free of charge, to any person obtaining a
/// copy of this software and associated documentation files (the "Software"),
/// to deal in the Software without restriction, including without limitation
/// the rights to use, copy, modify, merge, publish, distribute, sublicense,
/// and/or sell copies of the Software, and to permit persons to whom the
/// Software is furnished to do so, subject to the following conditions:
/// 
/// The above copyright notice and this permission notice (including the next
/// paragraph) shall be included in all copies or substantial portions of the
/// Software.
/// 
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
/// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
/// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
/// DEALINGS IN THE SOFTWARE.
/// 

library wayland;

import 'package:wayland/wayland.dart';
import 'package:wayland/protocols/wayland.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';
import 'package:result_dart/result_dart.dart';


/// manage sessions for applications
/// 
/// The xdg_session_manager_v1 interface defines base requests for creating and
/// managing a session for an application. Sessions persist across application
/// and compositor restarts unless explicitly destroyed. A session is created
/// for the purpose of maintaining an application's xdg_toplevel surfaces
/// across compositor or application restarts. The compositor should remember
/// as many states as possible for surfaces in a given session, but there is
/// no requirement for which states must be remembered.
/// 
/// Policies such as cache eviction are declared an implementation detail of
/// the compositor. Clients should account for no longer existing sessions.
/// 
class XdgSessionManagerV1 extends Proxy{
  final Context innerContext;
  final version = 1;

  XdgSessionManagerV1(this.innerContext) : super(innerContext.allocateClientId()){
    innerContext.register(this);
  }


@override
toString(){
return "XdgSessionManagerV1 {name: 'xdg_session_manager_v1', id: '$objectId', version: '1',}";
}

/// Destroy this object
/// 
/// Destroy the manager object. The existing session objects will be
/// unaffected.
/// 
  Result<void,Object> destroy() {
innerContext.unRegister(this);
    logLn("XdgSessionManagerV1::destroy ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 0]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in XdgSessionManagerV1::destroy: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// create or restore a session
/// 
/// Create a session object corresponding to either an existing session
/// identified by the given session identifier string or a new session.
/// While the session object exists, the session is considered to be "in
/// use".
/// 
/// If an identifier string represents a session that is currently actively
/// in use by the the same client, an 'in_use' error is raised. If some
/// other client is currently using the same session, the new session will
/// replace managing the associated state.
/// 
/// If the reason is not a valid enum entry, the 'invalid_reason' protocol
/// error is raised.
/// 
/// NULL is passed to initiate a new session. If a session_id is passed
/// which does not represent a valid session, the compositor treats it as if
/// NULL had been passed.
/// 
/// The session id string must be UTF-8 encoded. It is also limited by the
/// maximum length of wayland messages (around 4KB). The 'invalid_session_id'
/// protocol error will be raised if an invalid string is provided.
/// 
/// A client is allowed to have any number of in use sessions at the same
/// time.
/// 
/// [id]:
/// [reason]: reason for session
/// [session_id]: the session to restore
  Result<XdgSessionV1,Object> getSession(int reason, String sessionId) {
  var id =  XdgSessionV1(innerContext);
    logLn("XdgSessionManagerV1::getSession  id: $id reason: $reason sessionId: $sessionId");
var arguments = [id, reason, sessionId];var argTypes = <WaylandType>[WaylandType.newId, WaylandType.uint, WaylandType.string];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 1]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([id.objectId]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([reason]).buffer.asUint8List());
    final sessionIdBytes = utf8.encode(sessionId);
    bytesBuilder.add(Uint32List.fromList([sessionIdBytes.length + 1]).buffer.asUint8List());
    bytesBuilder.add(sessionIdBytes);
    bytesBuilder.add([0]); // Null terminator
    while (bytesBuilder.length % 4 != 0) { bytesBuilder.add([0]); } // Padding
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in XdgSessionManagerV1::getSession: $e");
   return Failure(e);
    }
    return Success(id);
  }

}

/// 
/// 

enum XdgSessionManagerV1Error {
/// a requested session is already in use
  inUse("in_use", 1),/// invalid session identifier
  invalidSessionId("invalid_session_id", 2),/// invalid reason
  invalidReason("invalid_reason", 3);
const XdgSessionManagerV1Error(this.enumName, this.enumValue);
final int enumValue;
final String enumName;
@override
toString(){
return "XdgSessionManagerV1Error {name: $enumName, value: $enumValue}";
}
}

/// reason for getting a session
/// 
/// The reason may determine in what way a session restores the window
/// management state of associated toplevels.
/// 
/// For example newly launched applications might be launched on the active
/// workspace with restored size and position, while a recovered
/// application might restore additional state such as active workspace and
/// stacking order.
/// 

enum XdgSessionManagerV1Reason {
/// 
  launch("launch", 1),/// 
  recover("recover", 2),/// 
  sessionRestore("session_restore", 3);
const XdgSessionManagerV1Reason(this.enumName, this.enumValue);
final int enumValue;
final String enumName;
@override
toString(){
return "XdgSessionManagerV1Reason {name: $enumName, value: $enumValue}";
}
}


/// newly-created session id
/// 
/// Emitted at most once some time after getting a new session object. It
/// means that no previous state was restored, and a new session was created.
/// The passed id can be persistently stored and used to restore previous
/// sessions.
/// 
class XdgSessionV1CreatedEvent {
/// 
  final String sessionId;

  XdgSessionV1CreatedEvent(
this.sessionId,

);

@override
toString(){
return "XdgSessionV1CreatedEvent (sessionId: $sessionId)";
}
}

typedef XdgSessionV1CreatedEventHandler = void Function(XdgSessionV1CreatedEvent);

/// the session has been restored
/// 
/// Emitted at most once some time after getting a new session object. It
/// means that previous state was at least partially restored. The same id
/// can again be used to restore previous sessions.
/// 
class XdgSessionV1RestoredEvent {
  XdgSessionV1RestoredEvent(
);

@override
toString(){
return "XdgSessionV1RestoredEvent ()";
}
}

typedef XdgSessionV1RestoredEventHandler = void Function(XdgSessionV1RestoredEvent);

/// the session has been replaced
/// 
/// Emitted at most once, if the session was taken over by some other
/// client. When this happens, the session and all its toplevel session
/// objects become inert, and should be destroyed.
/// 
class XdgSessionV1ReplacedEvent {
  XdgSessionV1ReplacedEvent(
);

@override
toString(){
return "XdgSessionV1ReplacedEvent ()";
}
}

typedef XdgSessionV1ReplacedEventHandler = void Function(XdgSessionV1ReplacedEvent);


/// A session for an application
/// 
/// A xdg_session_v1 object represents a session for an application. While the
/// object exists, all surfaces which have been added to the session will
/// have states stored by the compositor which can be reapplied at a later
/// time. Two sessions cannot exist for the same identifier string.
/// 
/// States for surfaces added to a session are automatically updated by the
/// compositor when they are changed.
/// 
class XdgSessionV1 extends Proxy implements Dispatcher{
  final Context innerContext;
  final version = 1;

  XdgSessionV1(this.innerContext) : super(innerContext.allocateClientId()){
    innerContext.register(this);
  }


@override
toString(){
return "XdgSessionV1 {name: 'xdg_session_v1', id: '$objectId', version: '1',}";
}

/// Destroy the session
/// 
/// Destroy a session object, preserving the current state but not continuing
/// to make further updates if state changes occur. This makes the associated
/// xdg_toplevel_session_v1 objects inert.
/// 
  Result<void,Object> destroy() {
innerContext.unRegister(this);
    logLn("XdgSessionV1::destroy ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 0]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in XdgSessionV1::destroy: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// Remove the session
/// 
/// Remove the session, making it no longer available for restoration. A
/// compositor should in response to this request remove the data related to
/// this session from its storage.
/// 
  Result<void,Object> remove() {
innerContext.unRegister(this);
    logLn("XdgSessionV1::remove ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 1]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in XdgSessionV1::remove: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// add a new surface to the session
/// 
/// Attempt to add a given surface to the session. The passed name is used
/// to identify what window is being restored, and may be used to store
/// window specific state within the session.
/// 
/// The name given to the toplevel must not correspond to any previously
/// existing toplevel names in the session. If the name matches an already
/// known toplevel name in the session, a 'name_in_use' protocol error will
/// be raised.
/// 
/// The toplevel object must not be added more than once to any session
/// created by the client, otherwise the 'already_added' protocol error
/// will be raised.
/// 
/// This request will return a xdg_toplevel_session_v1 for later
/// manipulation. As this resource is created from an empty initial state,
/// compositors must not emit a xdg_toplevel_session_v1.restored event for
/// resources created through this request.
/// 
/// The name string must be UTF-8 encoded. It is also limited by the maximum
/// length of wayland messages (around 4KB). The 'invalid_name' protocol
/// error will be raised if an invalid string is provided.
/// 
/// [id]:
/// [toplevel]:
/// [name]: name identifying the toplevel
  Result<XdgToplevelSessionV1,Object> addToplevel(XdgToplevel toplevel, String name) {
  var id =  XdgToplevelSessionV1(innerContext);
    logLn("XdgSessionV1::addToplevel  id: $id toplevel: $toplevel name: $name");
var arguments = [id, toplevel, name];var argTypes = <WaylandType>[WaylandType.newId, WaylandType.object, WaylandType.string];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 2]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([id.objectId]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([toplevel.objectId]).buffer.asUint8List());
    final nameBytes = utf8.encode(name);
    bytesBuilder.add(Uint32List.fromList([nameBytes.length + 1]).buffer.asUint8List());
    bytesBuilder.add(nameBytes);
    bytesBuilder.add([0]); // Null terminator
    while (bytesBuilder.length % 4 != 0) { bytesBuilder.add([0]); } // Padding
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in XdgSessionV1::addToplevel: $e");
   return Failure(e);
    }
    return Success(id);
  }

/// restore a surface state
/// 
/// Inform the compositor that the toplevel associated with the passed name
/// should have its window management state restored.
/// 
/// If the toplevel name was previously granted to another xdg_toplevel,
/// the 'name_in_use' protocol error will be raised.
/// 
/// The toplevel object must not be added more than once to any session
/// created by the client, otherwise the 'already_added' protocol error
/// will be raised.
/// 
/// This request must be called prior to the first commit on the associated
/// wl_surface after creating the toplevel, otherwise an 'already_mapped'
/// error is raised.
/// 
/// As part of the initial configure sequence, if the toplevel was
/// successfully restored, a xdg_toplevel_session_v1.restored event is
/// emitted. If the toplevel name was not known in the session, this request
/// will be equivalent to the xdg_toplevel_session_v1.add_toplevel request,
/// and no such event will be emitted. See the xdg_toplevel_session_v1.restored
/// event for further details.
/// 
/// The name string must be UTF-8 encoded. It is also limited by the maximum
/// length of wayland messages (around 4KB). The 'invalid_name' protocol
/// error will be raised if an invalid string is provided.
/// 
/// [id]:
/// [toplevel]:
/// [name]: name identifying the toplevel
  Result<XdgToplevelSessionV1,Object> restoreToplevel(XdgToplevel toplevel, String name) {
  var id =  XdgToplevelSessionV1(innerContext);
    logLn("XdgSessionV1::restoreToplevel  id: $id toplevel: $toplevel name: $name");
var arguments = [id, toplevel, name];var argTypes = <WaylandType>[WaylandType.newId, WaylandType.object, WaylandType.string];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 3]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([id.objectId]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([toplevel.objectId]).buffer.asUint8List());
    final nameBytes = utf8.encode(name);
    bytesBuilder.add(Uint32List.fromList([nameBytes.length + 1]).buffer.asUint8List());
    bytesBuilder.add(nameBytes);
    bytesBuilder.add([0]); // Null terminator
    while (bytesBuilder.length % 4 != 0) { bytesBuilder.add([0]); } // Padding
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in XdgSessionV1::restoreToplevel: $e");
   return Failure(e);
    }
    return Success(id);
  }

/// remove a surface from the session
/// 
/// Remove a specified surface from the session and render any related
/// xdg_toplevel_session_v1 object inert. The compositor should remove any
/// data related to the toplevel in the corresponding session from its internal
/// storage.
/// 
/// The window is specified by its name in the session. The name string
/// must be encoded in UTF-8, and it is limited in size by the maximum
/// length of wayland messages (around 4KB).
/// 
/// [name]: name identifying the toplevel
  Result<void,Object> removeToplevel(String name) {
    logLn("XdgSessionV1::removeToplevel  name: $name");
var arguments = [name];var argTypes = <WaylandType>[WaylandType.string];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 4]).buffer.asUint8List());
    final nameBytes = utf8.encode(name);
    bytesBuilder.add(Uint32List.fromList([nameBytes.length + 1]).buffer.asUint8List());
    bytesBuilder.add(nameBytes);
    bytesBuilder.add([0]); // Null terminator
    while (bytesBuilder.length % 4 != 0) { bytesBuilder.add([0]); } // Padding
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in XdgSessionV1::removeToplevel: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// newly-created session id
/// 
/// Emitted at most once some time after getting a new session object. It
/// means that no previous state was restored, and a new session was created.
/// The passed id can be persistently stored and used to restore previous
/// sessions.
/// 
/// Event handler for Created
/// - [session_id]:
 void onCreated(XdgSessionV1CreatedEventHandler handler) {
   _createdHandler = handler;
 }

 XdgSessionV1CreatedEventHandler? _createdHandler;

/// the session has been restored
/// 
/// Emitted at most once some time after getting a new session object. It
/// means that previous state was at least partially restored. The same id
/// can again be used to restore previous sessions.
/// 
/// Event handler for Restored
 void onRestored(XdgSessionV1RestoredEventHandler handler) {
   _restoredHandler = handler;
 }

 XdgSessionV1RestoredEventHandler? _restoredHandler;

/// the session has been replaced
/// 
/// Emitted at most once, if the session was taken over by some other
/// client. When this happens, the session and all its toplevel session
/// objects become inert, and should be destroyed.
/// 
/// Event handler for Replaced
 void onReplaced(XdgSessionV1ReplacedEventHandler handler) {
   _replacedHandler = handler;
 }

 XdgSessionV1ReplacedEventHandler? _replacedHandler;

 @override
 void dispatch(int opcode, int fd, Uint8List data) {
logLn("XdgSessionV1.dispatch($opcode, $fd, $data)");
   switch (opcode) {     case 0:

       if (_createdHandler != null) {
var _offset = 0;
final sessionIdLength = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final sessionId = utf8.decode(data.sublist(_offset, _offset + sessionIdLength - 1));
_offset += sessionIdLength; // Skip the string bytes and null terminator
while (_offset % 4 != 0) { _offset++; } // Padding
var event = XdgSessionV1CreatedEvent(
sessionId,
        );
         _createdHandler!(event);
       }
       break;
     case 1:

       if (_restoredHandler != null) {
         _restoredHandler!(XdgSessionV1RestoredEvent());
       }
       break;
     case 2:

       if (_replacedHandler != null) {
         _replacedHandler!(XdgSessionV1ReplacedEvent());
       }
       break;
   }
 }
}

/// 
/// 

enum XdgSessionV1Error {
/// toplevel name is already in use
  nameInUse("name_in_use", 1),/// toplevel was already mapped when restored
  alreadyMapped("already_mapped", 2),/// provided toplevel name is invalid
  invalidName("invalid_name", 3),/// toplevel already added
  alreadyAdded("already_added", 4);
const XdgSessionV1Error(this.enumName, this.enumValue);
final int enumValue;
final String enumName;
@override
toString(){
return "XdgSessionV1Error {name: $enumName, value: $enumValue}";
}
}


/// a toplevel's session has been restored
/// 
/// The "restored" event is emitted prior to the first
/// xdg_toplevel.configure for the toplevel. It will only be emitted after
/// xdg_session_v1.restore_toplevel, and the initial empty surface state has
/// been applied, and it indicates that the surface's session is being
/// restored with this configure event.
/// 
class XdgToplevelSessionV1RestoredEvent {
  XdgToplevelSessionV1RestoredEvent(
);

@override
toString(){
return "XdgToplevelSessionV1RestoredEvent ()";
}
}

typedef XdgToplevelSessionV1RestoredEventHandler = void Function(XdgToplevelSessionV1RestoredEvent);


/// A session for an application
/// 
/// A xdg_toplevel_session_v1 resource acts as a handle for the given
/// toplevel in the session. It allows for receiving events after a
/// toplevel state was restored, and has the requests to manage them.
/// 
class XdgToplevelSessionV1 extends Proxy implements Dispatcher{
  final Context innerContext;
  final version = 1;

  XdgToplevelSessionV1(this.innerContext) : super(innerContext.allocateClientId()){
    innerContext.register(this);
  }


@override
toString(){
return "XdgToplevelSessionV1 {name: 'xdg_toplevel_session_v1', id: '$objectId', version: '1',}";
}

/// Destroy the object
/// 
/// Destroy the object. This has no effect over window management of the
/// associated toplevel.
/// 
  Result<void,Object> destroy() {
innerContext.unRegister(this);
    logLn("XdgToplevelSessionV1::destroy ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 0]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in XdgToplevelSessionV1::destroy: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// change the name of toplevel session
/// 
/// Renames the toplevel session. The new name can be used in subsequent requests
/// to identify this session object. The state associated with this toplevel
/// session will be preserved.
/// 
/// If the xdg_session_v1 already contains a toplevel with the specified name,
/// the 'name_in_use' protocol error will be raised.
/// 
/// [name]: new name to identify the toplevel
  Result<void,Object> rename(String name) {
    logLn("XdgToplevelSessionV1::rename  name: $name");
var arguments = [name];var argTypes = <WaylandType>[WaylandType.string];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 1]).buffer.asUint8List());
    final nameBytes = utf8.encode(name);
    bytesBuilder.add(Uint32List.fromList([nameBytes.length + 1]).buffer.asUint8List());
    bytesBuilder.add(nameBytes);
    bytesBuilder.add([0]); // Null terminator
    while (bytesBuilder.length % 4 != 0) { bytesBuilder.add([0]); } // Padding
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in XdgToplevelSessionV1::rename: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// a toplevel's session has been restored
/// 
/// The "restored" event is emitted prior to the first
/// xdg_toplevel.configure for the toplevel. It will only be emitted after
/// xdg_session_v1.restore_toplevel, and the initial empty surface state has
/// been applied, and it indicates that the surface's session is being
/// restored with this configure event.
/// 
/// Event handler for Restored
 void onRestored(XdgToplevelSessionV1RestoredEventHandler handler) {
   _restoredHandler = handler;
 }

 XdgToplevelSessionV1RestoredEventHandler? _restoredHandler;

 @override
 void dispatch(int opcode, int fd, Uint8List data) {
logLn("XdgToplevelSessionV1.dispatch($opcode, $fd, $data)");
   switch (opcode) {     case 0:

       if (_restoredHandler != null) {
         _restoredHandler!(XdgToplevelSessionV1RestoredEvent());
       }
       break;
   }
 }
}

