// Generated by dart-wayland-scanner
// https://github.com/your-repo/dart-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/raw/master/unstable/wlr-export-dmabuf-unstable-v1.xml
//
// wlr_export_dmabuf_unstable_v1 Protocol Copyright: 
/// 
/// Copyright © 2018 Rostislav Pehlivanov
/// 
/// Permission is hereby granted, free of charge, to any person obtaining a
/// copy of this software and associated documentation files (the "Software"),
/// to deal in the Software without restriction, including without limitation
/// the rights to use, copy, modify, merge, publish, distribute, sublicense,
/// and/or sell copies of the Software, and to permit persons to whom the
/// Software is furnished to do so, subject to the following conditions:
/// 
/// The above copyright notice and this permission notice (including the next
/// paragraph) shall be included in all copies or substantial portions of the
/// Software.
/// 
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
/// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
/// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
/// DEALINGS IN THE SOFTWARE.
/// 

library wayland;

import 'package:wayland/wayland.dart';
import 'package:wayland/protocols/wayland.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';
import 'package:result_dart/result_dart.dart';


/// manager to inform clients and begin capturing
/// 
/// This object is a manager with which to start capturing from sources.
/// 
class ExportDmabufManagerV1 extends Proxy{
  final Context innerContext;
  final version = 1;

  ExportDmabufManagerV1(this.innerContext) : super(innerContext.allocateClientId()){
    innerContext.register(this);
  }


@override
toString(){
return "ExportDmabufManagerV1 {name: 'zwlr_export_dmabuf_manager_v1', id: '$objectId', version: '1',}";
}

/// capture a frame from an output
/// 
/// Capture the next frame of an entire output.
/// 
/// [frame]:
/// [overlay_cursor]: include custom client hardware cursor on top of the frame
/// [output]:
  Result<ExportDmabufFrameV1,Object> captureOutput(int overlayCursor, WlOutput output) {
  var frame =  ExportDmabufFrameV1(innerContext);
    logLn("ExportDmabufManagerV1::captureOutput  frame: $frame overlayCursor: $overlayCursor output: $output");
var arguments = [frame, overlayCursor, output];var argTypes = <WaylandType>[WaylandType.newId, WaylandType.int, WaylandType.object];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 0]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([frame.objectId]).buffer.asUint8List());
    bytesBuilder.add(Int32List.fromList([overlayCursor]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([output.objectId]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in ExportDmabufManagerV1::captureOutput: $e");
   return Failure(e);
    }
    return Success(frame);
  }

/// destroy the manager
/// 
/// All objects created by the manager will still remain valid, until their
/// appropriate destroy request has been called.
/// 
  Result<void,Object> destroy() {
innerContext.unRegister(this);
    logLn("ExportDmabufManagerV1::destroy ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 1]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in ExportDmabufManagerV1::destroy: $e");
   return Failure(e);
    }
    return Success(Object());
  }

}


/// a frame description
/// 
/// Main event supplying the client with information about the frame. If the
/// capture didn't fail, this event is always emitted first before any other
/// events.
/// 
/// This event is followed by a number of "object" as specified by the
/// "num_objects" argument.
/// 
class ExportDmabufFrameV1FrameEvent {
/// frame width in pixels
  final int width;

/// frame height in pixels
  final int height;

/// crop offset for the x axis
  final int offsetX;

/// crop offset for the y axis
  final int offsetY;

/// flags which indicate properties (invert, interlacing),
/// has the same values as zwp_linux_buffer_params_v1:flags
  final int bufferFlags;

/// indicates special frame features
  final int flags;

/// format of the frame (DRM_FORMAT_*)
  final int format;

/// drm format modifier, high
  final int modHigh;

/// drm format modifier, low
  final int modLow;

/// indicates how many objects (FDs) the frame has (max 4)
  final int numObjects;

  ExportDmabufFrameV1FrameEvent(
this.width,

this.height,

this.offsetX,

this.offsetY,

this.bufferFlags,

this.flags,

this.format,

this.modHigh,

this.modLow,

this.numObjects,

);

@override
toString(){
return "ExportDmabufFrameV1FrameEvent (width: $width, height: $height, offsetX: $offsetX, ..., modLow: $modLow, numObjects: $numObjects)";
}
}

typedef ExportDmabufFrameV1FrameEventHandler = void Function(ExportDmabufFrameV1FrameEvent);

/// an object description
/// 
/// Event which serves to supply the client with the file descriptors
/// containing the data for each object.
/// 
/// After receiving this event, the client must always close the file
/// descriptor as soon as they're done with it and even if the frame fails.
/// 
class ExportDmabufFrameV1ObjectEvent {
/// index of the current object
  final int index;

/// fd of the current object
  final int fd;

/// size in bytes for the current object
  final int size;

/// starting point for the data in the object's fd
  final int offset;

/// line size in bytes
  final int stride;

/// index of the plane the data in the object applies to
  final int planeIndex;

  ExportDmabufFrameV1ObjectEvent(
this.index,

this.fd,

this.size,

this.offset,

this.stride,

this.planeIndex,

);

@override
toString(){
return "ExportDmabufFrameV1ObjectEvent (index: $index, fd: $fd, size: $size, ..., stride: $stride, planeIndex: $planeIndex)";
}
}

typedef ExportDmabufFrameV1ObjectEventHandler = void Function(ExportDmabufFrameV1ObjectEvent);

/// indicates frame is available for reading
/// 
/// This event is sent as soon as the frame is presented, indicating it is
/// available for reading. This event includes the time at which
/// presentation happened at.
/// 
/// The timestamp is expressed as tv_sec_hi, tv_sec_lo, tv_nsec triples,
/// each component being an unsigned 32-bit value. Whole seconds are in
/// tv_sec which is a 64-bit value combined from tv_sec_hi and tv_sec_lo,
/// and the additional fractional part in tv_nsec as nanoseconds. Hence,
/// for valid timestamps tv_nsec must be in [0, 999999999]. The seconds part
/// may have an arbitrary offset at start.
/// 
/// After receiving this event, the client should destroy this object.
/// 
class ExportDmabufFrameV1ReadyEvent {
/// high 32 bits of the seconds part of the timestamp
  final int tvSecHi;

/// low 32 bits of the seconds part of the timestamp
  final int tvSecLo;

/// nanoseconds part of the timestamp
  final int tvNsec;

  ExportDmabufFrameV1ReadyEvent(
this.tvSecHi,

this.tvSecLo,

this.tvNsec,

);

@override
toString(){
return "ExportDmabufFrameV1ReadyEvent (tvSecHi: $tvSecHi, tvSecLo: $tvSecLo, tvNsec: $tvNsec)";
}
}

typedef ExportDmabufFrameV1ReadyEventHandler = void Function(ExportDmabufFrameV1ReadyEvent);

/// indicates the frame is no longer valid
/// 
/// If the capture failed or if the frame is no longer valid after the
/// "frame" event has been emitted, this event will be used to inform the
/// client to scrap the frame.
/// 
/// If the failure is temporary, the client may capture again the same
/// source. If the failure is permanent, any further attempts to capture the
/// same source will fail again.
/// 
/// After receiving this event, the client should destroy this object.
/// 
class ExportDmabufFrameV1CancelEvent {
/// indicates a reason for cancelling this frame capture
  final int reason;

  ExportDmabufFrameV1CancelEvent(
this.reason,

);

@override
toString(){
return "ExportDmabufFrameV1CancelEvent (reason: $reason)";
}
}

typedef ExportDmabufFrameV1CancelEventHandler = void Function(ExportDmabufFrameV1CancelEvent);


/// a DMA-BUF frame
/// 
/// This object represents a single DMA-BUF frame.
/// 
/// If the capture is successful, the compositor will first send a "frame"
/// event, followed by one or several "object". When the frame is available
/// for readout, the "ready" event is sent.
/// 
/// If the capture failed, the "cancel" event is sent. This can happen anytime
/// before the "ready" event.
/// 
/// Once either a "ready" or a "cancel" event is received, the client should
/// destroy the frame. Once an "object" event is received, the client is
/// responsible for closing the associated file descriptor.
/// 
/// All frames are read-only and may not be written into or altered.
/// 
class ExportDmabufFrameV1 extends Proxy implements Dispatcher{
  final Context innerContext;
  final version = 1;

  ExportDmabufFrameV1(this.innerContext) : super(innerContext.allocateClientId()){
    innerContext.register(this);
  }


@override
toString(){
return "ExportDmabufFrameV1 {name: 'zwlr_export_dmabuf_frame_v1', id: '$objectId', version: '1',}";
}

/// delete this object, used or not
/// 
/// Unreferences the frame. This request must be called as soon as it's no
/// longer used.
/// 
/// It can be called at any time by the client. The client will still have
/// to close any FDs it has been given.
/// 
  Result<void,Object> destroy() {
innerContext.unRegister(this);
    logLn("ExportDmabufFrameV1::destroy ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 0]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in ExportDmabufFrameV1::destroy: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// a frame description
/// 
/// Main event supplying the client with information about the frame. If the
/// capture didn't fail, this event is always emitted first before any other
/// events.
/// 
/// This event is followed by a number of "object" as specified by the
/// "num_objects" argument.
/// 
/// Event handler for Frame
/// - [width]: frame width in pixels
/// - [height]: frame height in pixels
/// - [offset_x]: crop offset for the x axis
/// - [offset_y]: crop offset for the y axis
/// - [buffer_flags]: flags which indicate properties (invert, interlacing),
/// has the same values as zwp_linux_buffer_params_v1:flags
/// - [flags]: indicates special frame features
/// - [format]: format of the frame (DRM_FORMAT_*)
/// - [mod_high]: drm format modifier, high
/// - [mod_low]: drm format modifier, low
/// - [num_objects]: indicates how many objects (FDs) the frame has (max 4)
 void onFrame(ExportDmabufFrameV1FrameEventHandler handler) {
   _frameHandler = handler;
 }

 ExportDmabufFrameV1FrameEventHandler? _frameHandler;

/// an object description
/// 
/// Event which serves to supply the client with the file descriptors
/// containing the data for each object.
/// 
/// After receiving this event, the client must always close the file
/// descriptor as soon as they're done with it and even if the frame fails.
/// 
/// Event handler for Object
/// - [index]: index of the current object
/// - [fd]: fd of the current object
/// - [size]: size in bytes for the current object
/// - [offset]: starting point for the data in the object's fd
/// - [stride]: line size in bytes
/// - [plane_index]: index of the plane the data in the object applies to
 void onObject(ExportDmabufFrameV1ObjectEventHandler handler) {
   _objectHandler = handler;
 }

 ExportDmabufFrameV1ObjectEventHandler? _objectHandler;

/// indicates frame is available for reading
/// 
/// This event is sent as soon as the frame is presented, indicating it is
/// available for reading. This event includes the time at which
/// presentation happened at.
/// 
/// The timestamp is expressed as tv_sec_hi, tv_sec_lo, tv_nsec triples,
/// each component being an unsigned 32-bit value. Whole seconds are in
/// tv_sec which is a 64-bit value combined from tv_sec_hi and tv_sec_lo,
/// and the additional fractional part in tv_nsec as nanoseconds. Hence,
/// for valid timestamps tv_nsec must be in [0, 999999999]. The seconds part
/// may have an arbitrary offset at start.
/// 
/// After receiving this event, the client should destroy this object.
/// 
/// Event handler for Ready
/// - [tv_sec_hi]: high 32 bits of the seconds part of the timestamp
/// - [tv_sec_lo]: low 32 bits of the seconds part of the timestamp
/// - [tv_nsec]: nanoseconds part of the timestamp
 void onReady(ExportDmabufFrameV1ReadyEventHandler handler) {
   _readyHandler = handler;
 }

 ExportDmabufFrameV1ReadyEventHandler? _readyHandler;

/// indicates the frame is no longer valid
/// 
/// If the capture failed or if the frame is no longer valid after the
/// "frame" event has been emitted, this event will be used to inform the
/// client to scrap the frame.
/// 
/// If the failure is temporary, the client may capture again the same
/// source. If the failure is permanent, any further attempts to capture the
/// same source will fail again.
/// 
/// After receiving this event, the client should destroy this object.
/// 
/// Event handler for Cancel
/// - [reason]: indicates a reason for cancelling this frame capture
 void onCancel(ExportDmabufFrameV1CancelEventHandler handler) {
   _cancelHandler = handler;
 }

 ExportDmabufFrameV1CancelEventHandler? _cancelHandler;

 @override
 void dispatch(int opcode, int fd, Uint8List data) {
logLn("ExportDmabufFrameV1.dispatch($opcode, $fd, $data)");
   switch (opcode) {     case 0:

       if (_frameHandler != null) {
var _offset = 0;
final width = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final height = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final offsetX = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final offsetY = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final bufferFlags = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final flags = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final format = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final modHigh = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final modLow = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final numObjects = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
var event = ExportDmabufFrameV1FrameEvent(
width,
height,
offsetX,
offsetY,
bufferFlags,
flags,
format,
modHigh,
modLow,
numObjects,
        );
         _frameHandler!(event);
       }
       break;
     case 1:
if(fd != -1){
}
       if (_objectHandler != null) {
var _offset = 0;
final index = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final fd2 = fd;
final size = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final offset = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final stride = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final planeIndex = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
var event = ExportDmabufFrameV1ObjectEvent(
index,
fd2,
size,
offset,
stride,
planeIndex,
        );
         _objectHandler!(event);
       }
       break;
     case 2:

       if (_readyHandler != null) {
var _offset = 0;
final tvSecHi = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final tvSecLo = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final tvNsec = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
var event = ExportDmabufFrameV1ReadyEvent(
tvSecHi,
tvSecLo,
tvNsec,
        );
         _readyHandler!(event);
       }
       break;
     case 3:

       if (_cancelHandler != null) {
var _offset = 0;
final reason = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
var event = ExportDmabufFrameV1CancelEvent(
reason,
        );
         _cancelHandler!(event);
       }
       break;
   }
 }
}

/// frame flags
/// 
/// Special flags that should be respected by the client.
/// 

enum ExportDmabufFrameV1Flags {
/// clients should copy frame before processing
  transient("transient", 0x1);
const ExportDmabufFrameV1Flags(this.enumName, this.enumValue);
final int enumValue;
final String enumName;
@override
toString(){
return "ExportDmabufFrameV1Flags {name: $enumName, value: $enumValue}";
}
}

/// cancel reason
/// 
/// Indicates reason for cancelling the frame.
/// 

enum ExportDmabufFrameV1CancelReason {
/// temporary error, source will produce more frames
  temporary("temporary", 0),/// fatal error, source will not produce frames
  permanent("permanent", 1),/// temporary error, source will produce more frames
  resizing("resizing", 2);
const ExportDmabufFrameV1CancelReason(this.enumName, this.enumValue);
final int enumValue;
final String enumName;
@override
toString(){
return "ExportDmabufFrameV1CancelReason {name: $enumName, value: $enumValue}";
}
}

