// Generated by dart-wayland-scanner
// https://github.com/your-repo/dart-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/raw/master/unstable/wlr-output-power-management-unstable-v1.xml
//
// wlr_output_power_management_unstable_v1 Protocol Copyright: 
/// 
/// Copyright © 2019 Purism SPC
/// 
/// Permission is hereby granted, free of charge, to any person obtaining a
/// copy of this software and associated documentation files (the "Software"),
/// to deal in the Software without restriction, including without limitation
/// the rights to use, copy, modify, merge, publish, distribute, sublicense,
/// and/or sell copies of the Software, and to permit persons to whom the
/// Software is furnished to do so, subject to the following conditions:
/// 
/// The above copyright notice and this permission notice (including the next
/// paragraph) shall be included in all copies or substantial portions of the
/// Software.
/// 
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
/// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
/// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
/// DEALINGS IN THE SOFTWARE.
/// 

library wayland;

import 'package:wayland/wayland.dart';
import 'package:wayland/protocols/wayland.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';
import 'package:result_dart/result_dart.dart';


/// manager to create per-output power management
/// 
/// This interface is a manager that allows creating per-output power
/// management mode controls.
/// 
class OutputPowerManagerV1 extends Proxy{
  final Context innerContext;
  final version = 1;

  OutputPowerManagerV1(this.innerContext) : super(innerContext.allocateClientId()){
    innerContext.register(this);
  }


@override
toString(){
return "OutputPowerManagerV1 {name: 'zwlr_output_power_manager_v1', id: '$objectId', version: '1',}";
}

/// get a power management for an output
/// 
/// Create an output power management mode control that can be used to
/// adjust the power management mode for a given output.
/// 
/// [id]:
/// [output]:
  Result<OutputPowerV1,Object> getOutputPower(WlOutput output) {
  var id =  OutputPowerV1(innerContext);
    logLn("OutputPowerManagerV1::getOutputPower  id: $id output: $output");
var arguments = [id, output];var argTypes = <WaylandType>[WaylandType.newId, WaylandType.object];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 0]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([id.objectId]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([output.objectId]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in OutputPowerManagerV1::getOutputPower: $e");
   return Failure(e);
    }
    return Success(id);
  }

/// destroy the manager
/// 
/// All objects created by the manager will still remain valid, until their
/// appropriate destroy request has been called.
/// 
  Result<void,Object> destroy() {
innerContext.unRegister(this);
    logLn("OutputPowerManagerV1::destroy ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 1]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in OutputPowerManagerV1::destroy: $e");
   return Failure(e);
    }
    return Success(Object());
  }

}


/// Report a power management mode change
/// 
/// Report the power management mode change of an output.
/// 
/// The mode event is sent after an output changed its power
/// management mode. The reason can be a client using set_mode or the
/// compositor deciding to change an output's mode.
/// This event is also sent immediately when the object is created
/// so the client is informed about the current power management mode.
/// 
class OutputPowerV1ModeEvent {
/// the output's new power management mode
  final int mode;

  OutputPowerV1ModeEvent(
this.mode,

);

@override
toString(){
return "OutputPowerV1ModeEvent (mode: $mode)";
}
}

typedef OutputPowerV1ModeEventHandler = void Function(OutputPowerV1ModeEvent);

/// object no longer valid
/// 
/// This event indicates that the output power management mode control
/// is no longer valid. This can happen for a number of reasons,
/// including:
/// - The output doesn't support power management
/// - Another client already has exclusive power management mode control
/// for this output
/// - The output disappeared
/// 
/// Upon receiving this event, the client should destroy this object.
/// 
class OutputPowerV1FailedEvent {
  OutputPowerV1FailedEvent(
);

@override
toString(){
return "OutputPowerV1FailedEvent ()";
}
}

typedef OutputPowerV1FailedEventHandler = void Function(OutputPowerV1FailedEvent);


/// adjust power management mode for an output
/// 
/// This object offers requests to set the power management mode of
/// an output.
/// 
class OutputPowerV1 extends Proxy implements Dispatcher{
  final Context innerContext;
  final version = 1;

  OutputPowerV1(this.innerContext) : super(innerContext.allocateClientId()){
    innerContext.register(this);
  }


@override
toString(){
return "OutputPowerV1 {name: 'zwlr_output_power_v1', id: '$objectId', version: '1',}";
}

/// Set an outputs power save mode
/// 
/// Set an output's power save mode to the given mode. The mode change
/// is effective immediately. If the output does not support the given
/// mode a failed event is sent.
/// 
/// [mode]: the power save mode to set
  Result<void,Object> setMode(int mode) {
    logLn("OutputPowerV1::setMode  mode: $mode");
var arguments = [mode];var argTypes = <WaylandType>[WaylandType.uint];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 0]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([mode]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in OutputPowerV1::setMode: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// destroy this power management
/// 
/// Destroys the output power management mode control object.
/// 
  Result<void,Object> destroy() {
innerContext.unRegister(this);
    logLn("OutputPowerV1::destroy ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 1]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in OutputPowerV1::destroy: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// Report a power management mode change
/// 
/// Report the power management mode change of an output.
/// 
/// The mode event is sent after an output changed its power
/// management mode. The reason can be a client using set_mode or the
/// compositor deciding to change an output's mode.
/// This event is also sent immediately when the object is created
/// so the client is informed about the current power management mode.
/// 
/// Event handler for Mode
/// - [mode]: the output's new power management mode
 void onMode(OutputPowerV1ModeEventHandler handler) {
   _modeHandler = handler;
 }

 OutputPowerV1ModeEventHandler? _modeHandler;

/// object no longer valid
/// 
/// This event indicates that the output power management mode control
/// is no longer valid. This can happen for a number of reasons,
/// including:
/// - The output doesn't support power management
/// - Another client already has exclusive power management mode control
/// for this output
/// - The output disappeared
/// 
/// Upon receiving this event, the client should destroy this object.
/// 
/// Event handler for Failed
 void onFailed(OutputPowerV1FailedEventHandler handler) {
   _failedHandler = handler;
 }

 OutputPowerV1FailedEventHandler? _failedHandler;

 @override
 void dispatch(int opcode, int fd, Uint8List data) {
logLn("OutputPowerV1.dispatch($opcode, $fd, $data)");
   switch (opcode) {     case 0:

       if (_modeHandler != null) {
var _offset = 0;
final mode = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
var event = OutputPowerV1ModeEvent(
mode,
        );
         _modeHandler!(event);
       }
       break;
     case 1:

       if (_failedHandler != null) {
         _failedHandler!(OutputPowerV1FailedEvent());
       }
       break;
   }
 }
}

/// 
/// 

enum OutputPowerV1Mode {
/// Output is turned off.
  off("off", 0),/// Output is turned on, no power saving
  on("on", 1);
const OutputPowerV1Mode(this.enumName, this.enumValue);
final int enumValue;
final String enumName;
@override
toString(){
return "OutputPowerV1Mode {name: $enumName, value: $enumValue}";
}
}

/// 
/// 

enum OutputPowerV1Error {
/// nonexistent power save mode
  invalidMode("invalid_mode", 1);
const OutputPowerV1Error(this.enumName, this.enumValue);
final int enumValue;
final String enumName;
@override
toString(){
return "OutputPowerV1Error {name: $enumName, value: $enumValue}";
}
}

