// Generated by dart-wayland-scanner
// https://github.com/your-repo/dart-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/raw/master/unstable/wlr-foreign-toplevel-management-unstable-v1.xml
//
// wlr_foreign_toplevel_management_unstable_v1 Protocol Copyright: 
/// 
/// Copyright © 2018 Ilia Bozhinov
/// 
/// Permission to use, copy, modify, distribute, and sell this
/// software and its documentation for any purpose is hereby granted
/// without fee, provided that the above copyright notice appear in
/// all copies and that both that copyright notice and this permission
/// notice appear in supporting documentation, and that the name of
/// the copyright holders not be used in advertising or publicity
/// pertaining to distribution of the software without specific,
/// written prior permission.  The copyright holders make no
/// representations about the suitability of this software for any
/// purpose.  It is provided "as is" without express or implied
/// warranty.
/// 
/// THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
/// SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
/// FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
/// SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
/// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
/// AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
/// ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
/// THIS SOFTWARE.
/// 

library wayland;

import 'package:wayland/wayland.dart';
import 'package:wayland/protocols/wayland.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';
import 'package:result_dart/result_dart.dart';

/// a toplevel has been created
/// 
/// This event is emitted whenever a new toplevel window is created. It
/// is emitted for all toplevels, regardless of the app that has created
/// them.
/// 
/// All initial details of the toplevel(title, app_id, states, etc.) will
/// be sent immediately after this event via the corresponding events in
/// zwlr_foreign_toplevel_handle_v1.
/// 
class ForeignToplevelManagerV1ToplevelEvent {
/// 
  final int toplevel;

  ForeignToplevelManagerV1ToplevelEvent(
this.toplevel,

);

@override
toString(){
return "ForeignToplevelManagerV1ToplevelEvent (toplevel: $toplevel)";
}
}

typedef ForeignToplevelManagerV1ToplevelEventHandler = void Function(ForeignToplevelManagerV1ToplevelEvent);

/// the compositor has finished with the toplevel manager
/// 
/// This event indicates that the compositor is done sending events to the
/// zwlr_foreign_toplevel_manager_v1. The server will destroy the object
/// immediately after sending this request, so it will become invalid and
/// the client should free any resources associated with it.
/// 
class ForeignToplevelManagerV1FinishedEvent {
  ForeignToplevelManagerV1FinishedEvent(
);

@override
toString(){
return "ForeignToplevelManagerV1FinishedEvent ()";
}
}

typedef ForeignToplevelManagerV1FinishedEventHandler = void Function(ForeignToplevelManagerV1FinishedEvent);


/// list and control opened apps
/// 
/// The purpose of this protocol is to enable the creation of taskbars
/// and docks by providing them with a list of opened applications and
/// letting them request certain actions on them, like maximizing, etc.
/// 
/// After a client binds the zwlr_foreign_toplevel_manager_v1, each opened
/// toplevel window will be sent via the toplevel event
/// 
class ForeignToplevelManagerV1 extends Proxy implements Dispatcher{
  final Context innerContext;
  final version = 3;

  ForeignToplevelManagerV1(this.innerContext) : super(innerContext.allocateClientId()){
    innerContext.register(this);
  }


@override
toString(){
return "ForeignToplevelManagerV1 {name: 'zwlr_foreign_toplevel_manager_v1', id: '$objectId', version: '3',}";
}

/// stop sending events
/// 
/// Indicates the client no longer wishes to receive events for new toplevels.
/// However the compositor may emit further toplevel_created events, until
/// the finished event is emitted.
/// 
/// The client must not send any more requests after this one.
/// 
  Result<void,Object> stop() {
    logLn("ForeignToplevelManagerV1::stop ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 0]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in ForeignToplevelManagerV1::stop: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// a toplevel has been created
/// 
/// This event is emitted whenever a new toplevel window is created. It
/// is emitted for all toplevels, regardless of the app that has created
/// them.
/// 
/// All initial details of the toplevel(title, app_id, states, etc.) will
/// be sent immediately after this event via the corresponding events in
/// zwlr_foreign_toplevel_handle_v1.
/// 
/// Event handler for Toplevel
/// - [toplevel]:
 void onToplevel(ForeignToplevelManagerV1ToplevelEventHandler handler) {
   _toplevelHandler = handler;
 }

 ForeignToplevelManagerV1ToplevelEventHandler? _toplevelHandler;

/// the compositor has finished with the toplevel manager
/// 
/// This event indicates that the compositor is done sending events to the
/// zwlr_foreign_toplevel_manager_v1. The server will destroy the object
/// immediately after sending this request, so it will become invalid and
/// the client should free any resources associated with it.
/// 
/// Event handler for Finished
 void onFinished(ForeignToplevelManagerV1FinishedEventHandler handler) {
   _finishedHandler = handler;
 }

 ForeignToplevelManagerV1FinishedEventHandler? _finishedHandler;

 @override
 void dispatch(int opcode, int fd, Uint8List data) {
logLn("ForeignToplevelManagerV1.dispatch($opcode, $fd, $data)");
   switch (opcode) {     case 0:

       if (_toplevelHandler != null) {
var _offset = 0;
final toplevel = innerContext.getProxy(ByteData.view(data.buffer).getUint32(_offset, Endian.little)).objectId;
_offset += 4;
var event = ForeignToplevelManagerV1ToplevelEvent(
toplevel,
        );
         _toplevelHandler!(event);
       }
       break;
     case 1:

       if (_finishedHandler != null) {
         _finishedHandler!(ForeignToplevelManagerV1FinishedEvent());
       }
       break;
   }
 }
}


/// title change
/// 
/// This event is emitted whenever the title of the toplevel changes.
/// 
class ForeignToplevelHandleV1TitleEvent {
/// 
  final String title;

  ForeignToplevelHandleV1TitleEvent(
this.title,

);

@override
toString(){
return "ForeignToplevelHandleV1TitleEvent (title: $title)";
}
}

typedef ForeignToplevelHandleV1TitleEventHandler = void Function(ForeignToplevelHandleV1TitleEvent);

/// app-id change
/// 
/// This event is emitted whenever the app-id of the toplevel changes.
/// 
class ForeignToplevelHandleV1AppIdEvent {
/// 
  final String appId;

  ForeignToplevelHandleV1AppIdEvent(
this.appId,

);

@override
toString(){
return "ForeignToplevelHandleV1AppIdEvent (appId: $appId)";
}
}

typedef ForeignToplevelHandleV1AppIdEventHandler = void Function(ForeignToplevelHandleV1AppIdEvent);

/// toplevel entered an output
/// 
/// This event is emitted whenever the toplevel becomes visible on
/// the given output. A toplevel may be visible on multiple outputs.
/// 
class ForeignToplevelHandleV1OutputEnterEvent {
/// 
  final int output;

  ForeignToplevelHandleV1OutputEnterEvent(
this.output,

);

@override
toString(){
return "ForeignToplevelHandleV1OutputEnterEvent (output: $output)";
}
}

typedef ForeignToplevelHandleV1OutputEnterEventHandler = void Function(ForeignToplevelHandleV1OutputEnterEvent);

/// toplevel left an output
/// 
/// This event is emitted whenever the toplevel stops being visible on
/// the given output. It is guaranteed that an entered-output event
/// with the same output has been emitted before this event.
/// 
class ForeignToplevelHandleV1OutputLeaveEvent {
/// 
  final int output;

  ForeignToplevelHandleV1OutputLeaveEvent(
this.output,

);

@override
toString(){
return "ForeignToplevelHandleV1OutputLeaveEvent (output: $output)";
}
}

typedef ForeignToplevelHandleV1OutputLeaveEventHandler = void Function(ForeignToplevelHandleV1OutputLeaveEvent);

/// the toplevel state changed
/// 
/// This event is emitted immediately after the zlw_foreign_toplevel_handle_v1
/// is created and each time the toplevel state changes, either because of a
/// compositor action or because of a request in this protocol.
/// 
class ForeignToplevelHandleV1StateEvent {
/// 
  final List<int> state;

  ForeignToplevelHandleV1StateEvent(
this.state,

);

@override
toString(){
return "ForeignToplevelHandleV1StateEvent (state: $state)";
}
}

typedef ForeignToplevelHandleV1StateEventHandler = void Function(ForeignToplevelHandleV1StateEvent);

/// all information about the toplevel has been sent
/// 
/// This event is sent after all changes in the toplevel state have been
/// sent.
/// 
/// This allows changes to the zwlr_foreign_toplevel_handle_v1 properties
/// to be seen as atomic, even if they happen via multiple events.
/// 
class ForeignToplevelHandleV1DoneEvent {
  ForeignToplevelHandleV1DoneEvent(
);

@override
toString(){
return "ForeignToplevelHandleV1DoneEvent ()";
}
}

typedef ForeignToplevelHandleV1DoneEventHandler = void Function(ForeignToplevelHandleV1DoneEvent);

/// this toplevel has been destroyed
/// 
/// This event means the toplevel has been destroyed. It is guaranteed there
/// won't be any more events for this zwlr_foreign_toplevel_handle_v1. The
/// toplevel itself becomes inert so any requests will be ignored except the
/// destroy request.
/// 
class ForeignToplevelHandleV1ClosedEvent {
  ForeignToplevelHandleV1ClosedEvent(
);

@override
toString(){
return "ForeignToplevelHandleV1ClosedEvent ()";
}
}

typedef ForeignToplevelHandleV1ClosedEventHandler = void Function(ForeignToplevelHandleV1ClosedEvent);

/// parent change
/// 
/// This event is emitted whenever the parent of the toplevel changes.
/// 
/// No event is emitted when the parent handle is destroyed by the client.
/// 
class ForeignToplevelHandleV1ParentEvent {
/// 
  final int parent;

  ForeignToplevelHandleV1ParentEvent(
this.parent,

);

@override
toString(){
return "ForeignToplevelHandleV1ParentEvent (parent: $parent)";
}
}

typedef ForeignToplevelHandleV1ParentEventHandler = void Function(ForeignToplevelHandleV1ParentEvent);


/// an opened toplevel
/// 
/// A zwlr_foreign_toplevel_handle_v1 object represents an opened toplevel
/// window. Each app may have multiple opened toplevels.
/// 
/// Each toplevel has a list of outputs it is visible on, conveyed to the
/// client with the output_enter and output_leave events.
/// 
class ForeignToplevelHandleV1 extends Proxy implements Dispatcher{
  final Context innerContext;
  final version = 3;

  ForeignToplevelHandleV1(this.innerContext) : super(innerContext.allocateClientId()){
    innerContext.register(this);
  }


@override
toString(){
return "ForeignToplevelHandleV1 {name: 'zwlr_foreign_toplevel_handle_v1', id: '$objectId', version: '3',}";
}

/// requests that the toplevel be maximized
/// 
/// Requests that the toplevel be maximized. If the maximized state actually
/// changes, this will be indicated by the state event.
/// 
  Result<void,Object> setMaximized() {
    logLn("ForeignToplevelHandleV1::setMaximized ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 0]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in ForeignToplevelHandleV1::setMaximized: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// requests that the toplevel be unmaximized
/// 
/// Requests that the toplevel be unmaximized. If the maximized state actually
/// changes, this will be indicated by the state event.
/// 
  Result<void,Object> unsetMaximized() {
    logLn("ForeignToplevelHandleV1::unsetMaximized ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 1]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in ForeignToplevelHandleV1::unsetMaximized: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// requests that the toplevel be minimized
/// 
/// Requests that the toplevel be minimized. If the minimized state actually
/// changes, this will be indicated by the state event.
/// 
  Result<void,Object> setMinimized() {
    logLn("ForeignToplevelHandleV1::setMinimized ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 2]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in ForeignToplevelHandleV1::setMinimized: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// requests that the toplevel be unminimized
/// 
/// Requests that the toplevel be unminimized. If the minimized state actually
/// changes, this will be indicated by the state event.
/// 
  Result<void,Object> unsetMinimized() {
    logLn("ForeignToplevelHandleV1::unsetMinimized ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 3]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in ForeignToplevelHandleV1::unsetMinimized: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// activate the toplevel
/// 
/// Request that this toplevel be activated on the given seat.
/// There is no guarantee the toplevel will be actually activated.
/// 
/// [seat]:
  Result<void,Object> activate(WlSeat seat) {
    logLn("ForeignToplevelHandleV1::activate  seat: $seat");
var arguments = [seat];var argTypes = <WaylandType>[WaylandType.object];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 4]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([seat.objectId]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in ForeignToplevelHandleV1::activate: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// request that the toplevel be closed
/// 
/// Send a request to the toplevel to close itself. The compositor would
/// typically use a shell-specific method to carry out this request, for
/// example by sending the xdg_toplevel.close event. However, this gives
/// no guarantees the toplevel will actually be destroyed. If and when
/// this happens, the zwlr_foreign_toplevel_handle_v1.closed event will
/// be emitted.
/// 
  Result<void,Object> close() {
    logLn("ForeignToplevelHandleV1::close ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 5]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in ForeignToplevelHandleV1::close: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// the rectangle which represents the toplevel
/// 
/// The rectangle of the surface specified in this request corresponds to
/// the place where the app using this protocol represents the given toplevel.
/// It can be used by the compositor as a hint for some operations, e.g
/// minimizing. The client is however not required to set this, in which
/// case the compositor is free to decide some default value.
/// 
/// If the client specifies more than one rectangle, only the last one is
/// considered.
/// 
/// The dimensions are given in surface-local coordinates.
/// Setting width=height=0 removes the already-set rectangle.
/// 
/// [surface]:
/// [x]:
/// [y]:
/// [width]:
/// [height]:
  Result<void,Object> setRectangle(WlSurface surface, int x, int y, int width, int height) {
    logLn("ForeignToplevelHandleV1::setRectangle  surface: $surface x: $x y: $y width: $width height: $height");
var arguments = [surface, x, y, width, height];var argTypes = <WaylandType>[WaylandType.object, WaylandType.int, WaylandType.int, WaylandType.int, WaylandType.int];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 6]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([surface.objectId]).buffer.asUint8List());
    bytesBuilder.add(Int32List.fromList([x]).buffer.asUint8List());
    bytesBuilder.add(Int32List.fromList([y]).buffer.asUint8List());
    bytesBuilder.add(Int32List.fromList([width]).buffer.asUint8List());
    bytesBuilder.add(Int32List.fromList([height]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in ForeignToplevelHandleV1::setRectangle: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// destroy the zwlr_foreign_toplevel_handle_v1 object
/// 
/// Destroys the zwlr_foreign_toplevel_handle_v1 object.
/// 
/// This request should be called either when the client does not want to
/// use the toplevel anymore or after the closed event to finalize the
/// destruction of the object.
/// 
  Result<void,Object> destroy() {
innerContext.unRegister(this);
    logLn("ForeignToplevelHandleV1::destroy ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 7]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in ForeignToplevelHandleV1::destroy: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// request that the toplevel be fullscreened
/// 
/// Requests that the toplevel be fullscreened on the given output. If the
/// fullscreen state and/or the outputs the toplevel is visible on actually
/// change, this will be indicated by the state and output_enter/leave
/// events.
/// 
/// The output parameter is only a hint to the compositor. Also, if output
/// is NULL, the compositor should decide which output the toplevel will be
/// fullscreened on, if at all.
/// 
/// [output]:
  Result<void,Object> setFullscreen(WlOutput output) {
    logLn("ForeignToplevelHandleV1::setFullscreen  output: $output");
var arguments = [output];var argTypes = <WaylandType>[WaylandType.object];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 8]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([output.objectId]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in ForeignToplevelHandleV1::setFullscreen: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// request that the toplevel be unfullscreened
/// 
/// Requests that the toplevel be unfullscreened. If the fullscreen state
/// actually changes, this will be indicated by the state event.
/// 
  Result<void,Object> unsetFullscreen() {
    logLn("ForeignToplevelHandleV1::unsetFullscreen ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 9]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in ForeignToplevelHandleV1::unsetFullscreen: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// title change
/// 
/// This event is emitted whenever the title of the toplevel changes.
/// 
/// Event handler for Title
/// - [title]:
 void onTitle(ForeignToplevelHandleV1TitleEventHandler handler) {
   _titleHandler = handler;
 }

 ForeignToplevelHandleV1TitleEventHandler? _titleHandler;

/// app-id change
/// 
/// This event is emitted whenever the app-id of the toplevel changes.
/// 
/// Event handler for AppId
/// - [app_id]:
 void onAppId(ForeignToplevelHandleV1AppIdEventHandler handler) {
   _appIdHandler = handler;
 }

 ForeignToplevelHandleV1AppIdEventHandler? _appIdHandler;

/// toplevel entered an output
/// 
/// This event is emitted whenever the toplevel becomes visible on
/// the given output. A toplevel may be visible on multiple outputs.
/// 
/// Event handler for OutputEnter
/// - [output]:
 void onOutputEnter(ForeignToplevelHandleV1OutputEnterEventHandler handler) {
   _outputEnterHandler = handler;
 }

 ForeignToplevelHandleV1OutputEnterEventHandler? _outputEnterHandler;

/// toplevel left an output
/// 
/// This event is emitted whenever the toplevel stops being visible on
/// the given output. It is guaranteed that an entered-output event
/// with the same output has been emitted before this event.
/// 
/// Event handler for OutputLeave
/// - [output]:
 void onOutputLeave(ForeignToplevelHandleV1OutputLeaveEventHandler handler) {
   _outputLeaveHandler = handler;
 }

 ForeignToplevelHandleV1OutputLeaveEventHandler? _outputLeaveHandler;

/// the toplevel state changed
/// 
/// This event is emitted immediately after the zlw_foreign_toplevel_handle_v1
/// is created and each time the toplevel state changes, either because of a
/// compositor action or because of a request in this protocol.
/// 
/// Event handler for State
/// - [state]:
 void onState(ForeignToplevelHandleV1StateEventHandler handler) {
   _stateHandler = handler;
 }

 ForeignToplevelHandleV1StateEventHandler? _stateHandler;

/// all information about the toplevel has been sent
/// 
/// This event is sent after all changes in the toplevel state have been
/// sent.
/// 
/// This allows changes to the zwlr_foreign_toplevel_handle_v1 properties
/// to be seen as atomic, even if they happen via multiple events.
/// 
/// Event handler for Done
 void onDone(ForeignToplevelHandleV1DoneEventHandler handler) {
   _doneHandler = handler;
 }

 ForeignToplevelHandleV1DoneEventHandler? _doneHandler;

/// this toplevel has been destroyed
/// 
/// This event means the toplevel has been destroyed. It is guaranteed there
/// won't be any more events for this zwlr_foreign_toplevel_handle_v1. The
/// toplevel itself becomes inert so any requests will be ignored except the
/// destroy request.
/// 
/// Event handler for Closed
 void onClosed(ForeignToplevelHandleV1ClosedEventHandler handler) {
   _closedHandler = handler;
 }

 ForeignToplevelHandleV1ClosedEventHandler? _closedHandler;

/// parent change
/// 
/// This event is emitted whenever the parent of the toplevel changes.
/// 
/// No event is emitted when the parent handle is destroyed by the client.
/// 
/// Event handler for Parent
/// - [parent]:
 void onParent(ForeignToplevelHandleV1ParentEventHandler handler) {
   _parentHandler = handler;
 }

 ForeignToplevelHandleV1ParentEventHandler? _parentHandler;

 @override
 void dispatch(int opcode, int fd, Uint8List data) {
logLn("ForeignToplevelHandleV1.dispatch($opcode, $fd, $data)");
   switch (opcode) {     case 0:

       if (_titleHandler != null) {
var _offset = 0;
final titleLength = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final title = utf8.decode(data.sublist(_offset, _offset + titleLength - 1));
_offset += titleLength; // Skip the string bytes and null terminator
while (_offset % 4 != 0) { _offset++; } // Padding
var event = ForeignToplevelHandleV1TitleEvent(
title,
        );
         _titleHandler!(event);
       }
       break;
     case 1:

       if (_appIdHandler != null) {
var _offset = 0;
final appIdLength = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4;
final appId = utf8.decode(data.sublist(_offset, _offset + appIdLength - 1));
_offset += appIdLength; // Skip the string bytes and null terminator
while (_offset % 4 != 0) { _offset++; } // Padding
var event = ForeignToplevelHandleV1AppIdEvent(
appId,
        );
         _appIdHandler!(event);
       }
       break;
     case 2:

       if (_outputEnterHandler != null) {
var _offset = 0;
final output = innerContext.getProxy(ByteData.view(data.buffer).getUint32(_offset, Endian.little)).objectId;
_offset += 4;
var event = ForeignToplevelHandleV1OutputEnterEvent(
output,
        );
         _outputEnterHandler!(event);
       }
       break;
     case 3:

       if (_outputLeaveHandler != null) {
var _offset = 0;
final output = innerContext.getProxy(ByteData.view(data.buffer).getUint32(_offset, Endian.little)).objectId;
_offset += 4;
var event = ForeignToplevelHandleV1OutputLeaveEvent(
output,
        );
         _outputLeaveHandler!(event);
       }
       break;
     case 4:

       if (_stateHandler != null) {
var _offset = 0;
final state = getArray(data, _offset);
var arrayLength = ByteData.view(data.buffer).getUint32(_offset, Endian.little);
_offset += 4 + arrayLength;
while (_offset % 4 != 0) { _offset++; } // Padding
var event = ForeignToplevelHandleV1StateEvent(
state,
        );
         _stateHandler!(event);
       }
       break;
     case 5:

       if (_doneHandler != null) {
         _doneHandler!(ForeignToplevelHandleV1DoneEvent());
       }
       break;
     case 6:

       if (_closedHandler != null) {
         _closedHandler!(ForeignToplevelHandleV1ClosedEvent());
       }
       break;
     case 7:

       if (_parentHandler != null) {
var _offset = 0;
final parent = innerContext.getProxy(ByteData.view(data.buffer).getUint32(_offset, Endian.little)).objectId;
_offset += 4;
var event = ForeignToplevelHandleV1ParentEvent(
parent,
        );
         _parentHandler!(event);
       }
       break;
   }
 }
}

/// types of states on the toplevel
/// 
/// The different states that a toplevel can have. These have the same meaning
/// as the states with the same names defined in xdg-toplevel
/// 

enum ForeignToplevelHandleV1State {
/// the toplevel is maximized
  maximized("maximized", 0),/// the toplevel is minimized
  minimized("minimized", 1),/// the toplevel is active
  activated("activated", 2),/// the toplevel is fullscreen
  fullscreen("fullscreen", 3);
const ForeignToplevelHandleV1State(this.enumName, this.enumValue);
final int enumValue;
final String enumName;
@override
toString(){
return "ForeignToplevelHandleV1State {name: $enumName, value: $enumValue}";
}
}

/// 
/// 

enum ForeignToplevelHandleV1Error {
/// the provided rectangle is invalid
  invalidRectangle("invalid_rectangle", 0);
const ForeignToplevelHandleV1Error(this.enumName, this.enumValue);
final int enumValue;
final String enumName;
@override
toString(){
return "ForeignToplevelHandleV1Error {name: $enumName, value: $enumValue}";
}
}

