// Generated by dart-wayland-scanner
// https://github.com/your-repo/dart-wayland-scanner
// XML file : https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/main/staging/pointer-warp/pointer-warp-v1.xml
//
// pointer_warp_v1 Protocol Copyright: 
/// 
/// Copyright © 2024 Neal Gompa
/// Copyright © 2024 Xaver Hugl
/// Copyright © 2024 Matthias Klumpp
/// Copyright © 2024 Vlad Zahorodnii
/// 
/// Permission is hereby granted, free of charge, to any person obtaining a
/// copy of this software and associated documentation files (the "Software"),
/// to deal in the Software without restriction, including without limitation
/// the rights to use, copy, modify, merge, publish, distribute, sublicense,
/// and/or sell copies of the Software, and to permit persons to whom the
/// Software is furnished to do so, subject to the following conditions:
/// The above copyright notice and this permission notice (including the next
/// paragraph) shall be included in all copies or substantial portions of the
/// Software.
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
/// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
/// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
/// DEALINGS IN THE SOFTWARE.
/// 

library wayland;

import 'package:wayland/wayland.dart';
import 'package:wayland/protocols/wayland.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';
import 'package:result_dart/result_dart.dart';


/// reposition the pointer to a location on a surface
/// 
/// This global interface allows applications to request the pointer to be
/// moved to a position relative to a wl_surface.
/// 
/// Note that if the desired behavior is to constrain the pointer to an area
/// or lock it to a position, this protocol does not provide a reliable way
/// to do that. The pointer constraint and pointer lock protocols should be
/// used for those use cases instead.
/// 
/// Warning! The protocol described in this file is currently in the testing
/// phase. Backward compatible changes may be added together with the
/// corresponding interface version bump. Backward incompatible changes can
/// only be done by creating a new major version of the extension.
/// 
class WpPointerWarpV1 extends Proxy{
  final Context innerContext;
  final version = 1;

  WpPointerWarpV1(this.innerContext) : super(innerContext.allocateClientId()){
    innerContext.register(this);
  }


@override
toString(){
return "WpPointerWarpV1 {name: 'wp_pointer_warp_v1', id: '$objectId', version: '1',}";
}

/// destroy the warp manager
/// 
/// Destroy the pointer warp manager.
/// 
  Result<void,Object> destroy() {
innerContext.unRegister(this);
    logLn("WpPointerWarpV1::destroy ");
var arguments = [];var argTypes = <WaylandType>[];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 0]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in WpPointerWarpV1::destroy: $e");
   return Failure(e);
    }
    return Success(Object());
  }

/// reposition the pointer
/// 
/// Request the compositor to move the pointer to a surface-local position.
/// Whether or not the compositor honors the request is implementation defined,
/// but it should
/// - honor it if the surface has pointer focus, including
/// when it has an implicit pointer grab
/// - reject it if the enter serial is incorrect
/// - reject it if the requested position is outside of the surface
/// 
/// Note that the enter serial is valid for any surface of the client,
/// and does not have to be from the surface the pointer is warped to.
/// 
/// 
/// [surface]: surface to position the pointer on
/// [pointer]: the pointer that should be repositioned
/// [x]:
/// [y]:
/// [serial]: serial number of the enter event
  Result<void,Object> warpPointer(WlSurface surface, WlPointer pointer, double x, double y, int serial) {
    logLn("WpPointerWarpV1::warpPointer  surface: $surface pointer: $pointer x: $x y: $y serial: $serial");
var arguments = [surface, pointer, x, y, serial];var argTypes = <WaylandType>[WaylandType.object, WaylandType.object, WaylandType.fixed, WaylandType.fixed, WaylandType.uint];
var calclulatedSize  = calculateSize(argTypes, arguments);
final bytesBuilder = BytesBuilder();
bytesBuilder.add(Uint32List.fromList([objectId, (calclulatedSize << 16) | 1]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([surface.objectId]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([pointer.objectId]).buffer.asUint8List());
    bytesBuilder.add(Int32List.fromList([doubleToFixed(x)]).buffer.asUint8List());
    bytesBuilder.add(Int32List.fromList([doubleToFixed(y)]).buffer.asUint8List());
    bytesBuilder.add(Uint32List.fromList([serial]).buffer.asUint8List());
    try{
    innerContext.sendMessage(bytesBuilder.toBytes(), );
    }catch (e) {
      logLn("Exception in WpPointerWarpV1::warpPointer: $e");
   return Failure(e);
    }
    return Success(Object());
  }

}

