// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

///
/// Regenerate bindings with `dart run ffigen`.
///
class Glut {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Glut(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Glut.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// I don't really know if it's a good idea... But here it goes:
  late final ffi.Pointer<ffi.Pointer<ffi.Void>> _glutStrokeRoman =
      _lookup<ffi.Pointer<ffi.Void>>('glutStrokeRoman');

  ffi.Pointer<ffi.Void> get glutStrokeRoman => _glutStrokeRoman.value;

  set glutStrokeRoman(ffi.Pointer<ffi.Void> value) =>
      _glutStrokeRoman.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Void>> _glutStrokeMonoRoman =
      _lookup<ffi.Pointer<ffi.Void>>('glutStrokeMonoRoman');

  ffi.Pointer<ffi.Void> get glutStrokeMonoRoman => _glutStrokeMonoRoman.value;

  set glutStrokeMonoRoman(ffi.Pointer<ffi.Void> value) =>
      _glutStrokeMonoRoman.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Void>> _glutBitmap9By15 =
      _lookup<ffi.Pointer<ffi.Void>>('glutBitmap9By15');

  ffi.Pointer<ffi.Void> get glutBitmap9By15 => _glutBitmap9By15.value;

  set glutBitmap9By15(ffi.Pointer<ffi.Void> value) =>
      _glutBitmap9By15.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Void>> _glutBitmap8By13 =
      _lookup<ffi.Pointer<ffi.Void>>('glutBitmap8By13');

  ffi.Pointer<ffi.Void> get glutBitmap8By13 => _glutBitmap8By13.value;

  set glutBitmap8By13(ffi.Pointer<ffi.Void> value) =>
      _glutBitmap8By13.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Void>> _glutBitmapTimesRoman10 =
      _lookup<ffi.Pointer<ffi.Void>>('glutBitmapTimesRoman10');

  ffi.Pointer<ffi.Void> get glutBitmapTimesRoman10 =>
      _glutBitmapTimesRoman10.value;

  set glutBitmapTimesRoman10(ffi.Pointer<ffi.Void> value) =>
      _glutBitmapTimesRoman10.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Void>> _glutBitmapTimesRoman24 =
      _lookup<ffi.Pointer<ffi.Void>>('glutBitmapTimesRoman24');

  ffi.Pointer<ffi.Void> get glutBitmapTimesRoman24 =>
      _glutBitmapTimesRoman24.value;

  set glutBitmapTimesRoman24(ffi.Pointer<ffi.Void> value) =>
      _glutBitmapTimesRoman24.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Void>> _glutBitmapHelvetica10 =
      _lookup<ffi.Pointer<ffi.Void>>('glutBitmapHelvetica10');

  ffi.Pointer<ffi.Void> get glutBitmapHelvetica10 =>
      _glutBitmapHelvetica10.value;

  set glutBitmapHelvetica10(ffi.Pointer<ffi.Void> value) =>
      _glutBitmapHelvetica10.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Void>> _glutBitmapHelvetica12 =
      _lookup<ffi.Pointer<ffi.Void>>('glutBitmapHelvetica12');

  ffi.Pointer<ffi.Void> get glutBitmapHelvetica12 =>
      _glutBitmapHelvetica12.value;

  set glutBitmapHelvetica12(ffi.Pointer<ffi.Void> value) =>
      _glutBitmapHelvetica12.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Void>> _glutBitmapHelvetica18 =
      _lookup<ffi.Pointer<ffi.Void>>('glutBitmapHelvetica18');

  ffi.Pointer<ffi.Void> get glutBitmapHelvetica18 =>
      _glutBitmapHelvetica18.value;

  set glutBitmapHelvetica18(ffi.Pointer<ffi.Void> value) =>
      _glutBitmapHelvetica18.value = value;
}

const int FREEGLUT = 1;

const int GLUT_API_VERSION = 4;

const int GLUT_XLIB_IMPLEMENTATION = 13;

const int FREEGLUT_VERSION_2_0 = 1;

const int GLUT_KEY_F1 = 1;

const int GLUT_KEY_F2 = 2;

const int GLUT_KEY_F3 = 3;

const int GLUT_KEY_F4 = 4;

const int GLUT_KEY_F5 = 5;

const int GLUT_KEY_F6 = 6;

const int GLUT_KEY_F7 = 7;

const int GLUT_KEY_F8 = 8;

const int GLUT_KEY_F9 = 9;

const int GLUT_KEY_F10 = 10;

const int GLUT_KEY_F11 = 11;

const int GLUT_KEY_F12 = 12;

const int GLUT_KEY_LEFT = 100;

const int GLUT_KEY_UP = 101;

const int GLUT_KEY_RIGHT = 102;

const int GLUT_KEY_DOWN = 103;

const int GLUT_KEY_PAGE_UP = 104;

const int GLUT_KEY_PAGE_DOWN = 105;

const int GLUT_KEY_HOME = 106;

const int GLUT_KEY_END = 107;

const int GLUT_KEY_INSERT = 108;

const int GLUT_LEFT_BUTTON = 0;

const int GLUT_MIDDLE_BUTTON = 1;

const int GLUT_RIGHT_BUTTON = 2;

const int GLUT_DOWN = 0;

const int GLUT_UP = 1;

const int GLUT_LEFT = 0;

const int GLUT_ENTERED = 1;

const int GLUT_RGB = 0;

const int GLUT_RGBA = 0;

const int GLUT_INDEX = 1;

const int GLUT_SINGLE = 0;

const int GLUT_DOUBLE = 2;

const int GLUT_ACCUM = 4;

const int GLUT_ALPHA = 8;

const int GLUT_DEPTH = 16;

const int GLUT_STENCIL = 32;

const int GLUT_MULTISAMPLE = 128;

const int GLUT_STEREO = 256;

const int GLUT_LUMINANCE = 512;

const int GLUT_MENU_NOT_IN_USE = 0;

const int GLUT_MENU_IN_USE = 1;

const int GLUT_NOT_VISIBLE = 0;

const int GLUT_VISIBLE = 1;

const int GLUT_HIDDEN = 0;

const int GLUT_FULLY_RETAINED = 1;

const int GLUT_PARTIALLY_RETAINED = 2;

const int GLUT_FULLY_COVERED = 3;

const int GLUT_WINDOW_X = 100;

const int GLUT_WINDOW_Y = 101;

const int GLUT_WINDOW_WIDTH = 102;

const int GLUT_WINDOW_HEIGHT = 103;

const int GLUT_WINDOW_BUFFER_SIZE = 104;

const int GLUT_WINDOW_STENCIL_SIZE = 105;

const int GLUT_WINDOW_DEPTH_SIZE = 106;

const int GLUT_WINDOW_RED_SIZE = 107;

const int GLUT_WINDOW_GREEN_SIZE = 108;

const int GLUT_WINDOW_BLUE_SIZE = 109;

const int GLUT_WINDOW_ALPHA_SIZE = 110;

const int GLUT_WINDOW_ACCUM_RED_SIZE = 111;

const int GLUT_WINDOW_ACCUM_GREEN_SIZE = 112;

const int GLUT_WINDOW_ACCUM_BLUE_SIZE = 113;

const int GLUT_WINDOW_ACCUM_ALPHA_SIZE = 114;

const int GLUT_WINDOW_DOUBLEBUFFER = 115;

const int GLUT_WINDOW_RGBA = 116;

const int GLUT_WINDOW_PARENT = 117;

const int GLUT_WINDOW_NUM_CHILDREN = 118;

const int GLUT_WINDOW_COLORMAP_SIZE = 119;

const int GLUT_WINDOW_NUM_SAMPLES = 120;

const int GLUT_WINDOW_STEREO = 121;

const int GLUT_WINDOW_CURSOR = 122;

const int GLUT_SCREEN_WIDTH = 200;

const int GLUT_SCREEN_HEIGHT = 201;

const int GLUT_SCREEN_WIDTH_MM = 202;

const int GLUT_SCREEN_HEIGHT_MM = 203;

const int GLUT_MENU_NUM_ITEMS = 300;

const int GLUT_DISPLAY_MODE_POSSIBLE = 400;

const int GLUT_INIT_WINDOW_X = 500;

const int GLUT_INIT_WINDOW_Y = 501;

const int GLUT_INIT_WINDOW_WIDTH = 502;

const int GLUT_INIT_WINDOW_HEIGHT = 503;

const int GLUT_INIT_DISPLAY_MODE = 504;

const int GLUT_ELAPSED_TIME = 700;

const int GLUT_WINDOW_FORMAT_ID = 123;

const int GLUT_HAS_KEYBOARD = 600;

const int GLUT_HAS_MOUSE = 601;

const int GLUT_HAS_SPACEBALL = 602;

const int GLUT_HAS_DIAL_AND_BUTTON_BOX = 603;

const int GLUT_HAS_TABLET = 604;

const int GLUT_NUM_MOUSE_BUTTONS = 605;

const int GLUT_NUM_SPACEBALL_BUTTONS = 606;

const int GLUT_NUM_BUTTON_BOX_BUTTONS = 607;

const int GLUT_NUM_DIALS = 608;

const int GLUT_NUM_TABLET_BUTTONS = 609;

const int GLUT_DEVICE_IGNORE_KEY_REPEAT = 610;

const int GLUT_DEVICE_KEY_REPEAT = 611;

const int GLUT_HAS_JOYSTICK = 612;

const int GLUT_OWNS_JOYSTICK = 613;

const int GLUT_JOYSTICK_BUTTONS = 614;

const int GLUT_JOYSTICK_AXES = 615;

const int GLUT_JOYSTICK_POLL_RATE = 616;

const int GLUT_OVERLAY_POSSIBLE = 800;

const int GLUT_LAYER_IN_USE = 801;

const int GLUT_HAS_OVERLAY = 802;

const int GLUT_TRANSPARENT_INDEX = 803;

const int GLUT_NORMAL_DAMAGED = 804;

const int GLUT_OVERLAY_DAMAGED = 805;

const int GLUT_VIDEO_RESIZE_POSSIBLE = 900;

const int GLUT_VIDEO_RESIZE_IN_USE = 901;

const int GLUT_VIDEO_RESIZE_X_DELTA = 902;

const int GLUT_VIDEO_RESIZE_Y_DELTA = 903;

const int GLUT_VIDEO_RESIZE_WIDTH_DELTA = 904;

const int GLUT_VIDEO_RESIZE_HEIGHT_DELTA = 905;

const int GLUT_VIDEO_RESIZE_X = 906;

const int GLUT_VIDEO_RESIZE_Y = 907;

const int GLUT_VIDEO_RESIZE_WIDTH = 908;

const int GLUT_VIDEO_RESIZE_HEIGHT = 909;

const int GLUT_NORMAL = 0;

const int GLUT_OVERLAY = 1;

const int GLUT_ACTIVE_SHIFT = 1;

const int GLUT_ACTIVE_CTRL = 2;

const int GLUT_ACTIVE_ALT = 4;

const int GLUT_CURSOR_RIGHT_ARROW = 0;

const int GLUT_CURSOR_LEFT_ARROW = 1;

const int GLUT_CURSOR_INFO = 2;

const int GLUT_CURSOR_DESTROY = 3;

const int GLUT_CURSOR_HELP = 4;

const int GLUT_CURSOR_CYCLE = 5;

const int GLUT_CURSOR_SPRAY = 6;

const int GLUT_CURSOR_WAIT = 7;

const int GLUT_CURSOR_TEXT = 8;

const int GLUT_CURSOR_CROSSHAIR = 9;

const int GLUT_CURSOR_UP_DOWN = 10;

const int GLUT_CURSOR_LEFT_RIGHT = 11;

const int GLUT_CURSOR_TOP_SIDE = 12;

const int GLUT_CURSOR_BOTTOM_SIDE = 13;

const int GLUT_CURSOR_LEFT_SIDE = 14;

const int GLUT_CURSOR_RIGHT_SIDE = 15;

const int GLUT_CURSOR_TOP_LEFT_CORNER = 16;

const int GLUT_CURSOR_TOP_RIGHT_CORNER = 17;

const int GLUT_CURSOR_BOTTOM_RIGHT_CORNER = 18;

const int GLUT_CURSOR_BOTTOM_LEFT_CORNER = 19;

const int GLUT_CURSOR_INHERIT = 100;

const int GLUT_CURSOR_NONE = 101;

const int GLUT_CURSOR_FULL_CROSSHAIR = 102;

const int GLUT_RED = 0;

const int GLUT_GREEN = 1;

const int GLUT_BLUE = 2;

const int GLUT_KEY_REPEAT_OFF = 0;

const int GLUT_KEY_REPEAT_ON = 1;

const int GLUT_KEY_REPEAT_DEFAULT = 2;

const int GLUT_JOYSTICK_BUTTON_A = 1;

const int GLUT_JOYSTICK_BUTTON_B = 2;

const int GLUT_JOYSTICK_BUTTON_C = 4;

const int GLUT_JOYSTICK_BUTTON_D = 8;

const int GLUT_GAME_MODE_ACTIVE = 0;

const int GLUT_GAME_MODE_POSSIBLE = 1;

const int GLUT_GAME_MODE_WIDTH = 2;

const int GLUT_GAME_MODE_HEIGHT = 3;

const int GLUT_GAME_MODE_PIXEL_DEPTH = 4;

const int GLUT_GAME_MODE_REFRESH_RATE = 5;

const int GLUT_GAME_MODE_DISPLAY_CHANGED = 6;
