name: bardash
description: A customizable Wayland bar powered by wayland-toolkit and Lua config.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  window_toolkit: any
  lualike: ^0.5.2
  dbus: ^0.7.14
  ffi: ^2.2.0
  wayland: any
  code_assets: any
  hooks: any
  native_toolchain_c: any
  logging: any
dev_dependencies:
  skia_dart: any
  code_assets: any
  hooks: any
  logging: any
  native_toolchain_c: any
  ffigen: ^20.1.1
  test: any
