name: example
description: Wayland client examples
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  wayland:
    path: ../
  image:
  pcanvas: ^1.1.0

dependency_overrides:
  native_socket:
    path: /home/kingwill101/code/dart_packages/native_socket
